#!/usr/bin/perl

use strict;
use warnings;
use FindBin qw($Bin);

my $app = "websaver";
my $tag = "trunk";

`grep -A1 CFBundleShortVersionString $tag/Info.plist` =~ /<string>([\d\.]+)<\/string>/;

my $version = $1 || die "Cauld not get version from $app";
print "Creating [$app-$version.dmg]\n";

system("cd $tag && xcodebuild -alltargets clean")
    && die "Clean failed: $?";

system("cd $tag && xcodebuild -alltargets");
    && die "Build failed: $?";

system("hdiutil create -srcfolder $tag/build/Release -volname $app-$version $app-$version.dmg");
    && die "Disk image failed: $?";

system("$Bin/support/googlecode_upload.py", "--summary", "$app v$version", "--labels", "OpSys-OSX,Type-Archive", "--project", "$app", "$app-$version.dmg")
   && die "Upload returned: $?";

print "Done.\n";

exit 0;

# vim: expandtab sw=4 ts=4 sts=4:

